# Generated by Django 3.0.4 on 2020-04-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
